### ISSUE TITLE
Add Oh My Zsh by default

### ISSUE THREAD

**Issue by Anahkiasen** [madewithlove/skeletor#8]
If possible

https://github.com/madewithlove/vaprobash-scripts/blob/master/zsh.sh

**Comment by dietervds** [comment]
I'm not sure if it's the best course of action atm. Even Vaprobash itself doesn't seem to like it anymore, since it throws up some issues here and there regarding paths.
And those are -not- pleasant issues to deal with :)
http://cl.ly/image/102M200V1K1H

**Comment by Anahkiasen** [comment]
It caused issues at the time because of RVM and NVM, as they rely on being installed in the .zprofile file and he installed ZSH and the end. That's why _our_ script joins it with it, with RVM and NVM already in it. I provision it all the time by hand, never had any issue really, it's just an matter of order

**Comment by dietervds** [comment]
Ok, will try it out.

**Comment by Anahkiasen** [comment]
Do a test and see if with a provision both RVM and NVM still work. If not, at least add a custom .profile nonetheless with the `cd /vagrant` and the PATH changes so the boxes are a little less raw
