### ISSUE TITLE
Setup Marvel with ElasticSearch

### ISSUE THREAD

**Issue by Anahkiasen** [madewithlove/skeletor#9]
We currently use [Sense](https://chrome.google.com/webstore/detail/sense-beta/lhjgkmllcaadmopgmanpapmpjgmfcfig) to debug our ES clusters. However if you look at said plugin's [Github](https://github.com/cheics/sense) it has actually been abandoned and integrated into ES itself under the [Marvel](http://www.elasticsearch.org/overview/marvel/) plugin.

Installing pretty much consists of three lines:

``` bash
cd /usr/share/elasticsearch
sudo bin/plugin -i elasticsearch/marvel/latest
sudo service elasticsearch restart
```

You can then access Marvel at (per example) `remindme.dev:9200/_plugin/marvel`. It's a general HQ that gives all informations you need about the current ES installation:

![screenshot 2015-02-25 01 18 48](https://cloud.githubusercontent.com/assets/1321596/6362330/46698e1a-bc8c-11e4-853f-c1fcb1e319f7.png)

And Sense is integrated into it, can be found in the dropdown on the top right:

![screenshot 2015-02-25 01 14 47](https://cloud.githubusercontent.com/assets/1321596/6362305/f7ec9278-bc8b-11e4-9d7b-b8ce05c77211.png)

**Comment by Anahkiasen** [comment]
cc @dieterve

**Comment by dieterve** [comment]
Cool, Marvel is using Kibana for the statistics in HQ, I have been wanting to play with that.

What is the memory usage of Kibana? We already need to increase our VM's RAM to be workable, so need to take Kibana's requirements into account as well.

The browser plugin does have the advantage that you can connect to any Elasticsearch server (for example production) and run queries on that. Looking at the screenshot is probably still possible, but only requires you to boot the VM (which is not that much of a big deal).

Have you noticed any big feature differences between the 2 Sense versions? I am guessing its mostly about sorting new versions of ES.

**Comment by Anahkiasen** [comment]
Most the autocomplete is more up to date and tell you which type which fields expect etc. As ES versions keep coming out the differences between the two will probably become more significant, considering ES's habit of breaking BC.

I didn't notice any memory difference on the VM I tested it on, but would probably need to make a more advanced benchmark.

The chrome version can indeed let us access other servers, nothing prevents us from using both really. Marvel for local VMs and the extension for remote servers. Marvel has a price, it's only free for development so I wouldn't recommend setting it up without a license elsewhere than the VMs

**Comment by Anahkiasen** [comment]
Marvel is now part of Kibana and it's a whole thing to set it up in local, much more annoying so.
